package edu.buffalo.cse.irf14.analysis;

import java.util.HashMap;
import java.util.Map;

public class ContractionsCollection {

	public static Map<String, String> populateCOntractionMap() {
		Map<String, String> contractionsMap = new HashMap<String, String>();
		// small case
		contractionsMap.put("ain't", "am not");
		contractionsMap.put("aren't", "are not");
		contractionsMap.put("can't", "cannot");
		contractionsMap.put("could've", "could have");
		contractionsMap.put("couldn't", "could not");
		contractionsMap.put("couldn't've", "could not have");
		contractionsMap.put("didn't", "did not");
		contractionsMap.put("doesn't", "does not");
		contractionsMap.put("don't", "do not");
		contractionsMap.put("hadn't", "had not");
		contractionsMap.put("hadn't've", "had not have");
		contractionsMap.put("hasn't", "has not");
		contractionsMap.put("haven't", "have not");
		contractionsMap.put("he'd", "he would");
		contractionsMap.put("he'd've", "he would have");
		contractionsMap.put("he'll", "he will");
		contractionsMap.put("he's", "he has");
		contractionsMap.put("how'd", "how would");
		contractionsMap.put("how'll", "how will");
		contractionsMap.put("how's", "how is");
		contractionsMap.put("i'd", "i would");
		contractionsMap.put("i'd've", "i would have");
		contractionsMap.put("i'll", "i will");
		contractionsMap.put("i'm", "i am");
		contractionsMap.put("i've", "i have");
		contractionsMap.put("isn't", "is not");
		contractionsMap.put("it'd", "it would");
		contractionsMap.put("it'd've", "it would have");
		contractionsMap.put("it'll", "it will");
		contractionsMap.put("it's", "it is");
		contractionsMap.put("let's", "let us");
		contractionsMap.put("ma'am", "madam");
		contractionsMap.put("mightn't", "might not");
		contractionsMap.put("mightn't've", "might not have");
		contractionsMap.put("might've", "might have");
		contractionsMap.put("mustn't", "must not");
		contractionsMap.put("must've", "must have");
		contractionsMap.put("needn't", "need not");
		contractionsMap.put("not've", "not have");
		contractionsMap.put("o'clock", "of the clock");
		contractionsMap.put("shan't", "shall not");
		contractionsMap.put("she'd", "she would");
		contractionsMap.put("she'd've", "she would have");
		contractionsMap.put("she'll", "she will");
		contractionsMap.put("she's", "she is");
		contractionsMap.put("should've", "should have");
		contractionsMap.put("shouldn't", "should not");
		contractionsMap.put("shouldn't've", "should not have");
		contractionsMap.put("that's", "that is");
		contractionsMap.put("there'd", "there would");
		contractionsMap.put("there'd've", "there would have");
		contractionsMap.put("there're", "there are");
		contractionsMap.put("there's", "there is");
		contractionsMap.put("they'd", "they would");
		contractionsMap.put("they'd've", "they would have");
		contractionsMap.put("they'll", "they will");
		contractionsMap.put("they're", "they are");
		contractionsMap.put("they've", "they have");
		contractionsMap.put("wasn't", "was not");
		contractionsMap.put("we'd", "we would");
		contractionsMap.put("we'd've", "we would have");
		contractionsMap.put("we'll", "we will");
		contractionsMap.put("we're", "we are");
		contractionsMap.put("we've", "we have");
		contractionsMap.put("weren't", "were not");
		contractionsMap.put("what'll", "what will");
		contractionsMap.put("what're", "what are");
		contractionsMap.put("what's", "what is");
		contractionsMap.put("what've", "what have");
		contractionsMap.put("when's", "when is");
		contractionsMap.put("where'd", "where did");
		contractionsMap.put("where's", "where is");
		contractionsMap.put("where've", "where have");
		contractionsMap.put("who'd", "who would");
		contractionsMap.put("who'll", "who will");
		contractionsMap.put("who're", "who are");
		contractionsMap.put("who's", "who is");
		contractionsMap.put("who've", "who have");
		contractionsMap.put("why'll", "why will");
		contractionsMap.put("why're", "why are");
		contractionsMap.put("why's", "why is");
		contractionsMap.put("won't", "will not");
		contractionsMap.put("would've", "would have");
		contractionsMap.put("wouldn't", "would not");
		contractionsMap.put("wouldn't've", "would not have");
		contractionsMap.put("y'all", "you all");
		contractionsMap.put("y'all'd've", "you all would have");
		contractionsMap.put("you'd", "you would");
		contractionsMap.put("you'd've", "you would have");
		contractionsMap.put("you'll", "you will");
		contractionsMap.put("you're", "you are");
		contractionsMap.put("you've", "you have");

		contractionsMap.put("Ain't", "Am not");
		contractionsMap.put("Aren't", "Are not");
		contractionsMap.put("Can't", "Cannot");
		contractionsMap.put("Could've", "Could have");
		contractionsMap.put("Couldn't", "Could not");
		contractionsMap.put("Couldn't've", "Could not have");
		contractionsMap.put("Didn't", "Did not");
		contractionsMap.put("Doesn't", "Does not");
		contractionsMap.put("Don't", "Do not");
		contractionsMap.put("Hadn't", "Had not");
		contractionsMap.put("Hadn't've", "Had not have");
		contractionsMap.put("Hasn't", "Has not");
		contractionsMap.put("Haven't", "Have not");
		contractionsMap.put("He'd", "He would");
		contractionsMap.put("He'd've", "He would have");
		contractionsMap.put("He'll", "He will");
		contractionsMap.put("He's", "He has");
		contractionsMap.put("How'd", "How would");
		contractionsMap.put("How'll", "How will");
		contractionsMap.put("How's", "How is");
		contractionsMap.put("I'd", "I would");
		contractionsMap.put("I'd've", "I would have");
		contractionsMap.put("I'll", "I will");
		contractionsMap.put("I'm", "I am");
		contractionsMap.put("I've", "I have");
		contractionsMap.put("Isn't", "Is not");
		contractionsMap.put("It'd", "It would");
		contractionsMap.put("It'd've", "It would have");
		contractionsMap.put("It'll", "It will");
		contractionsMap.put("It's", "It is");
		contractionsMap.put("Let's", "Let us");
		contractionsMap.put("Ma'am", "Madam");
		contractionsMap.put("Mightn't", "Might not");
		contractionsMap.put("Mightn't've", "Might not have");
		contractionsMap.put("Might've", "Might have");
		contractionsMap.put("Mustn't", "Must not");
		contractionsMap.put("Must've", "Must have");
		contractionsMap.put("Needn't", "Need not");
		contractionsMap.put("Not've", "Not have");
		contractionsMap.put("O'clock", "of the clock");
		contractionsMap.put("Shan't", "Shall not");
		contractionsMap.put("She'd", "She would");
		contractionsMap.put("She'd've", "She would have");
		contractionsMap.put("She'll", "She will");
		contractionsMap.put("She's", "She is");
		contractionsMap.put("Should've", "Should have");
		contractionsMap.put("Shouldn't", "Should not");
		contractionsMap.put("Shouldn't've", "Should not have");
		contractionsMap.put("That's", "That is");
		contractionsMap.put("There'd", "There would");
		contractionsMap.put("There'd've", "There would have");
		contractionsMap.put("There're", "There are");
		contractionsMap.put("There's", "There is");
		contractionsMap.put("They'd", "They would");
		contractionsMap.put("They'd've", "They would have");
		contractionsMap.put("They'll", "They will");
		contractionsMap.put("They're", "They are");
		contractionsMap.put("They've", "They have");
		contractionsMap.put("Wasn't", "Was not");
		contractionsMap.put("We'd", "We would");
		contractionsMap.put("We'd've", "We would have");
		contractionsMap.put("We'll", "We will");
		contractionsMap.put("We're", "We are");
		contractionsMap.put("We've", "We have");
		contractionsMap.put("Weren't", "Were not");
		contractionsMap.put("What'll", "What will");
		contractionsMap.put("What're", "What are");
		contractionsMap.put("What's", "What is");
		contractionsMap.put("What've", "What have");
		contractionsMap.put("When's", "When is");
		contractionsMap.put("Where'd", "Where did");
		contractionsMap.put("Where's", "Where is");
		contractionsMap.put("Where've", "Where have");
		contractionsMap.put("Who'd", "Who would");
		contractionsMap.put("Who'll", "Who will");
		contractionsMap.put("Who're", "Who are");
		contractionsMap.put("Who's", "Who is");
		contractionsMap.put("Who've", "Who have");
		contractionsMap.put("Why'll", "Why will");
		contractionsMap.put("Why're", "Why are");
		contractionsMap.put("Why's", "Why is");
		contractionsMap.put("Won't", "Will not");
		contractionsMap.put("Would've", "Would have");
		contractionsMap.put("Wouldn't", "Would not");
		contractionsMap.put("Wouldn't've", "Would not have");
		contractionsMap.put("Y'all", "You all");
		contractionsMap.put("Y'all'd've", "You all would have");
		contractionsMap.put("You'd", "You would");
		contractionsMap.put("You'd've", "You would have");
		contractionsMap.put("You'll", "You will");
		contractionsMap.put("You're", "You are");
		contractionsMap.put("You've", "You have");
		contractionsMap.put("'em", "them");
		return contractionsMap;
	}

}
